apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: image-registry.apps.2.rahti.csc.fi/sdx-assignment-nhantran/react-frontend:latest
        ports:
        - containerPort: 3000 # Ensure this matches the app's listening port
        env:
        - name: PORT
          value: "3000" # Ensures the app listens on this port
        readinessProbe:
          httpGet:
            path: /
            port: 3000 # Ensure your app serves content at `/`
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  ports:
  - port: 3000 # Expose the same port as the app
    targetPort: 3000 # Map to container's 3000
  selector:
    app: react-frontend

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: react-frontend-route
spec:
  to:
    kind: Service
    name: react-frontend-service
  port:
    targetPort: 3000 # Match the exposed service port
  tls:
    termination: edge # Enable HTTPS for external traffic
